export const ROLES = {
  ADMIN: "ADMIN",
  DRIVER: "DRIVER",
  GUEST: "GUEST",
};

export const DRIVER_STATUS = {
  AVAILABLE: "AVAILABLE",
  ASSIGNED: "ASSIGNED",
  ON_BREAK: "ON_BREAK",
  OFFLINE: "OFFLINE",
};

export const RIDE_STATUS = {
  PENDING: "PENDING",
  ASSIGNED: "ASSIGNED",
  ARRIVED: "ARRIVED",
  PICKED_UP: "PICKED_UP",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};